name: imod_coupler

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - build
  - geopandas
  - isort
  - loguru
  - mypy
  - numpy
  - pandas
  - pip
  - pip:
      - bmi-python
      - git+https://gitlab.com/deltares/imod/imod-python.git@fd4d71293a434b9d8d3fbf65b12f2f235867fd7b
      - HYDROLIB-core
      - pydantic
      - xmipy
  - pydantic
  - pydata-sphinx-theme
  - pytest
  - pytest-xdist
  - pytest-cases
  - pytest-dotenv
  - python=3.10
  - pywin32
  - rasterio>=1.0
  - scipy
  - sphinx
  - tomli
  - tomli-w
  - twine
  - xarray
