# This environment is used for compiling iMOD Coupler with pyinstaller
name: imod_coupler_minimal

channels:
  - conda-forge
  - defaults

dependencies:
  - h5netcdf
  - loguru
  - numpy
  - pydantic
  - pyinstaller
  - python=3.10
  - scipy
  - tomli
  - tomli-w
  - xmipy
