# This environment is used to develop on iMOD Coupler
name: imod_coupler

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - build
  - geopandas
  - loguru
  - mypy
  - netcdf4
  - numpy
  - pip
  - pip:
      - imod>=0.11.6
      - "git+https://github.com/Deltares/Ribasim.git#egg=ribasim_api&subdirectory=python/ribasim_api"
  - pydantic
  - pydata-sphinx-theme
  - pytest
  - pytest-cases
  - pytest-dotenv
  - pytest-xdist
  - python=3.10
  - rasterio>=1.0
  - ruff
  - scipy
  - sphinx
  - tomli
  - tomli-w
  - twine
  - xmipy
