# This environment is used for compiling iMOD Coupler with pyinstaller
name: imod_coupler_minimal

channels:
  - conda-forge
  - defaults

dependencies:
  - loguru
  - netcdf4=1.6.3 # TODO: Investigate pyinstaller error for 1.6.4
  - numpy
  - pip
  - pip:
    - "git+https://github.com/Deltares/Ribasim.git#egg=ribasim_api&subdirectory=python/ribasim_api"
  - pydantic
  - pyinstaller
  - python=3.10
  - scipy
  - tomli
  - tomli-w
  - xmipy
