# This environment is used to develop on iMOD Coupler
name: imod_coupler

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - build
  - geopandas
  - h5netcdf
  - loguru
  - mypy
  - numpy
  - pip
  - pip:
      - "git+https://gitlab.com/deltares/imod/imod-python.git@master2"
      - "git+https://github.com/Deltares/Ribasim.git/#subdirectory=python/ribasim"
      - "git+https://github.com/Deltares/Ribasim.git/#subdirectory=python/ribasim_api"
      - "git+https://github.com/Deltares/Ribasim.git/#subdirectory=python/ribasim_testmodels"
  - pydantic=1
  - pytest
  - pytest-cases
  - pytest-dotenv
  - pytest-xdist
  - python=3.10
  - rasterio>=1.0
  - ruff
  - scipy
  - tomli
  - tomli-w
  - twine
  - xmipy
