name: Check Packages

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          environment-file: ./environment.yml
      - name: Install imod coupler
        run: |
          pip install -e .
      - name: Build and check packages
        run: |
          python -m build
          twine check --strict dist/*
