name: Check Packages

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install lint dependencies
        run: |
          pip install -e ".[check-packages]"
      - name: Build and check packages
        run: |
          python -m build
          twine check --strict dist/*
