name: Check Packages

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          cache-env: true
      - name: Install "check-packages" dependencies
        run: |
          pip install build twine
      - name: Build and check packages
        run: |
          python -m build
          twine check --strict dist/*
