name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
      - name: Install lint dependencies
        run: |
          pip install -e ".[lint]"
      - name: Run black
        run: black --check .
      - name: Run isort
        run: isort --check .
      - name: Run flake8
        run: flake8
