name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v1
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          cache-env: true
      - name: Run black
        run: |
          black --check .
      - name: Run isort
        run: |
          isort --check .
      - name: Run mypy (strict) on imod_coupler
        run: |
          mypy --non-interactive --ignore-missing-imports --strict imod_coupler

      - name: Run mypy on tests
        run: |
          mypy --non-interactive --ignore-missing-imports tests
