name: Ribasim Python Tests
on:
  push:
    branches: [main, update/pixi-lock]
    paths-ignore: [".teamcity/**"]
    tags: ["*"]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Python ${{ matrix.pixi-environment }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        pixi-environment:
          - py312
          - py311
          - py310
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"
      - name: Prepare pixi
        run: pixi run --environment ${{ matrix.pixi-environment }} install
      - name: Test Ribasim Python
        run: pixi run --environment ${{ matrix.pixi-environment }} test-primod
        env: 
          METASWAP_LOOKUP_TABLE: dummy/path/to/lookup_table
